/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package divinen.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Item extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 185686953058518427L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Item\",\"namespace\":\"divinen.avro\",\"fields\":[{\"name\":\"itemId\",\"type\":\"string\"},{\"name\":\"availableQuantity\",\"type\":[\"int\"]},{\"name\":\"distributionCenterId\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence itemId;
  @Deprecated public java.lang.Object availableQuantity;
  @Deprecated public java.lang.CharSequence distributionCenterId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Item() {}

  /**
   * All-args constructor.
   * @param itemId The new value for itemId
   * @param availableQuantity The new value for availableQuantity
   * @param distributionCenterId The new value for distributionCenterId
   */
  public Item(java.lang.CharSequence itemId, java.lang.Object availableQuantity, java.lang.CharSequence distributionCenterId) {
    this.itemId = itemId;
    this.availableQuantity = availableQuantity;
    this.distributionCenterId = distributionCenterId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return itemId;
    case 1: return availableQuantity;
    case 2: return distributionCenterId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: itemId = (java.lang.CharSequence)value$; break;
    case 1: availableQuantity = (java.lang.Object)value$; break;
    case 2: distributionCenterId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'itemId' field.
   * @return The value of the 'itemId' field.
   */
  public java.lang.CharSequence getItemId() {
    return itemId;
  }

  /**
   * Sets the value of the 'itemId' field.
   * @param value the value to set.
   */
  public void setItemId(java.lang.CharSequence value) {
    this.itemId = value;
  }

  /**
   * Gets the value of the 'availableQuantity' field.
   * @return The value of the 'availableQuantity' field.
   */
  public java.lang.Object getAvailableQuantity() {
    return availableQuantity;
  }

  /**
   * Sets the value of the 'availableQuantity' field.
   * @param value the value to set.
   */
  public void setAvailableQuantity(java.lang.Object value) {
    this.availableQuantity = value;
  }

  /**
   * Gets the value of the 'distributionCenterId' field.
   * @return The value of the 'distributionCenterId' field.
   */
  public java.lang.CharSequence getDistributionCenterId() {
    return distributionCenterId;
  }

  /**
   * Sets the value of the 'distributionCenterId' field.
   * @param value the value to set.
   */
  public void setDistributionCenterId(java.lang.CharSequence value) {
    this.distributionCenterId = value;
  }

  /**
   * Creates a new Item RecordBuilder.
   * @return A new Item RecordBuilder
   */
  public static divinen.avro.Item.Builder newBuilder() {
    return new divinen.avro.Item.Builder();
  }

  /**
   * Creates a new Item RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Item RecordBuilder
   */
  public static divinen.avro.Item.Builder newBuilder(divinen.avro.Item.Builder other) {
    return new divinen.avro.Item.Builder(other);
  }

  /**
   * Creates a new Item RecordBuilder by copying an existing Item instance.
   * @param other The existing instance to copy.
   * @return A new Item RecordBuilder
   */
  public static divinen.avro.Item.Builder newBuilder(divinen.avro.Item other) {
    return new divinen.avro.Item.Builder(other);
  }

  /**
   * RecordBuilder for Item instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Item>
    implements org.apache.avro.data.RecordBuilder<Item> {

    private java.lang.CharSequence itemId;
    private java.lang.Object availableQuantity;
    private java.lang.CharSequence distributionCenterId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(divinen.avro.Item.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.availableQuantity)) {
        this.availableQuantity = data().deepCopy(fields()[1].schema(), other.availableQuantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.distributionCenterId)) {
        this.distributionCenterId = data().deepCopy(fields()[2].schema(), other.distributionCenterId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Item instance
     * @param other The existing instance to copy.
     */
    private Builder(divinen.avro.Item other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.availableQuantity)) {
        this.availableQuantity = data().deepCopy(fields()[1].schema(), other.availableQuantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.distributionCenterId)) {
        this.distributionCenterId = data().deepCopy(fields()[2].schema(), other.distributionCenterId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'itemId' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemId() {
      return itemId;
    }

    /**
      * Sets the value of the 'itemId' field.
      * @param value The value of 'itemId'.
      * @return This builder.
      */
    public divinen.avro.Item.Builder setItemId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.itemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'itemId' field has been set.
      * @return True if the 'itemId' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'itemId' field.
      * @return This builder.
      */
    public divinen.avro.Item.Builder clearItemId() {
      itemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'availableQuantity' field.
      * @return The value.
      */
    public java.lang.Object getAvailableQuantity() {
      return availableQuantity;
    }

    /**
      * Sets the value of the 'availableQuantity' field.
      * @param value The value of 'availableQuantity'.
      * @return This builder.
      */
    public divinen.avro.Item.Builder setAvailableQuantity(java.lang.Object value) {
      validate(fields()[1], value);
      this.availableQuantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'availableQuantity' field has been set.
      * @return True if the 'availableQuantity' field has been set, false otherwise.
      */
    public boolean hasAvailableQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'availableQuantity' field.
      * @return This builder.
      */
    public divinen.avro.Item.Builder clearAvailableQuantity() {
      availableQuantity = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'distributionCenterId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDistributionCenterId() {
      return distributionCenterId;
    }

    /**
      * Sets the value of the 'distributionCenterId' field.
      * @param value The value of 'distributionCenterId'.
      * @return This builder.
      */
    public divinen.avro.Item.Builder setDistributionCenterId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.distributionCenterId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'distributionCenterId' field has been set.
      * @return True if the 'distributionCenterId' field has been set, false otherwise.
      */
    public boolean hasDistributionCenterId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'distributionCenterId' field.
      * @return This builder.
      */
    public divinen.avro.Item.Builder clearDistributionCenterId() {
      distributionCenterId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Item build() {
      try {
        Item record = new Item();
        record.itemId = fieldSetFlags()[0] ? this.itemId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.availableQuantity = fieldSetFlags()[1] ? this.availableQuantity : (java.lang.Object) defaultValue(fields()[1]);
        record.distributionCenterId = fieldSetFlags()[2] ? this.distributionCenterId : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
